credentials:
  usernames:
    user_placeholder:
      email: user@lazyapply.ai
      name: Temp User
      password: "abc123"

cookie:
  expiry_days: 30
  key: ${COOKIE_KEY}
  name: lazyapply_cookie

oauth:
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
  github:
    client_id: ${GITHUB_CLIENT_ID}
    client_secret: ${GITHUB_CLIENT_SECRET}
